[build]
target = "thumbv7em-none-eabihf" # Example target for Cortex-M4F

[target.'thumbv7em-none-eabihf']
runner = "probe-run --chip STM32F407VGT6" # Example runner

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["panic_immediate_abort"]
