name: Test embed-check Installation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Lint embed-check.sh
        run: shellcheck embed-check.sh

  bats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bats
        run: sudo apt-get update && sudo apt-get install -y bats
      - name: Run Bats tests
        run: |
          if [ -d test ]; then
            bats test/
          else
            echo "No tests found."
          fi

  test-install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Set up shell
        uses: actions/checkout@v3
      - name: Install embed-check
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            curl -sSL https://raw.githubusercontent.com/shawal-mbalire/embed-check/master/embed-check.sh -o embed-check.sh
            bash embed-check.sh list
          else
            curl -sSL https://raw.githubusercontent.com/shawal-mbalire/embed-check/master/embed-check.sh | sudo tee /usr/local/bin/embed-check > /dev/null
            sudo chmod +x /usr/local/bin/embed-check
            embed-check list
          fi 